(function(){
'use strict';
const K='sls_next_';
const cards=[
 ['🏠','Personal Dashboard','Continue learning, streak and weekly progress','dashboard'],['🗺️','Learning Roadmap','Beginner → N1 guided path','roadmap'],['🧪','Smart Quiz','Random practice and weak-topic review','quiz'],['📈','Progress Analytics','Study and quiz activity overview','analytics'],['🔔','Smart Notifications','Choose your study reminders','notify'],['🏆','XP & Level System','Earn XP, levels and achievements','xp'],['📝','Writing Checker','Basic sentence guidance and study notes','writing'],['🎤','Pronunciation Practice','Record and listen to your practice','pronunciation'],['📖','Vocabulary Notebook','Save words for later revision','vocab'],['👥','Study Groups','N5, N4 and N3 community spaces','groups'],['❓','Q&A Section','Ask and organize study questions','qa'],['🛡️','User Moderation','Admin moderation workspace','moderation'],['📝','Audit Log','Track important admin actions','audit'],['💾','Backup / Export','Export your learning data','backup']
];
const hub=document.getElementById('sls-next-hub'),grid=document.getElementById('sls-next-grid'),modal=document.getElementById('sls-next-modal'),content=document.getElementById('sls-next-content');
cards.forEach(c=>{const d=document.createElement('button');d.type='button';d.className='slsh-card';d.dataset.feature=c[3];d.innerHTML='<span class="i">'+c[0]+'</span><b>'+c[1]+'</b><small>'+c[2]+'</small>';grid.appendChild(d)});
function loggedIn(){try{return !!(window.auth&&window.auth.currentUser)}catch(e){return !!document.querySelector('[data-logged-in="true"]')}}
function showHub(){hub.style.display=loggedIn()?'block':'none'}
setInterval(showHub,2500);document.addEventListener('click',e=>{if(e.target.closest('.slsh-card'))open(e.target.closest('.slsh-card').dataset.feature);if(e.target===modal||e.target.closest('.x'))close()});
function close(){modal.style.display='none';content.innerHTML=''}function open(f){modal.style.display='block';render[f]&&render[f]();}
function save(n,v){localStorage.setItem(K+n,JSON.stringify(v))}function load(n,d){try{return JSON.parse(localStorage.getItem(K+n))??d}catch(e){return d}}
function html(t,b){content.innerHTML='<h2>'+t+'</h2>'+b}
const render={
 dashboard(){const xp=load('xp',0),tasks=load('tasks',[]),words=load('words',[]);html('🏠 Personal Dashboard','<div class="slsh-box"><b>Welcome back!</b><p>XP: '+xp+' · Saved words: '+words.length+' · Planner tasks: '+tasks.length+'</p><div class="slsh-progress"><i style="width:'+Math.min(100,xp%500/5)+'%"></i></div></div><div class="slsh-row"><div class="slsh-box">🔥 Study streak<br><b>'+load('streak',0)+' days</b></div><div class="slsh-box">📚 Continue Learning<br><b>Open your next saved resource</b></div></div>')},
 roadmap(){html('🗺️ Japanese Learning Roadmap','<div class="slsh-box">Beginner → Hiragana & Katakana → JLPT N5 → N4 → N3 → N2 → N1</div><p>Complete milestones from your existing Learning Path feature; this roadmap provides the expanded overview.</p>')},
 quiz(){let q=['What is the Japanese word for water?','Choose the particle often used to mark a topic:'];html('🧪 Smart Quiz','<div class="slsh-box"><p>'+q[Math.floor(Math.random()*q.length)]+'</p><input id="sq" class="slsh-input" placeholder="Your answer"><button class="slsh-btn" id="sqb">Check & save attempt</button><p id="sqr"></p></div><p>Quiz attempts are saved locally for this device and can be used as a lightweight progress history.</p>');document.getElementById('sqb').onclick=()=>{let a=load('quizAttempts',[]);a.push({at:Date.now(),answer:document.getElementById('sq').value});save('quizAttempts',a);document.getElementById('sqr').textContent='Attempt saved. Review your weak topics in your existing quiz tools.'}},
 analytics(){let a=load('quizAttempts',[]),xp=load('xp',0);html('📈 Personal Progress Analytics','<div class="slsh-box">Quiz attempts: <b>'+a.length+'</b></div><div class="slsh-box">XP earned: <b>'+xp+'</b><div class="slsh-progress"><i style="width:'+Math.min(100,xp/10)+'%"></i></div></div><p>For richer analytics, your existing Firebase analytics dashboard remains the main source of site-wide statistics.</p>')},
 notify(){html('🔔 Smart Notifications','<div class="slsh-box"><label><input type="checkbox" id="n1"> Daily challenge reminder</label><br><label><input type="checkbox" id="n2"> Study planner reminder</label><br><label><input type="checkbox" id="n3"> New resource updates</label><br><br><button class="slsh-btn" id="ns">Save preferences</button></div>');['n1','n2','n3'].forEach((id,i)=>document.getElementById(id).checked=load('notify',[false,false,false])[i]);document.getElementById('ns').onclick=()=>{save('notify',['n1','n2','n3'].map(x=>document.getElementById(x).checked));alert('Notification preferences saved. Browser permission is still required for actual notifications.')}},
 xp(){let xp=load('xp',0),level=Math.floor(xp/500)+1;html('🏆 XP & Level System','<div class="slsh-box"><h3>Level '+level+'</h3><p>'+xp+' XP earned</p><button class="slsh-btn" id="xpb">Add 10 practice XP</button></div><p>Achievements can be connected to your existing badges system.</p>');document.getElementById('xpb').onclick=()=>{save('xp',xp+10);save('streak',Math.max(1,load('streak',0)));render.xp()}},
 writing(){html('📝 Japanese Writing Checker','<textarea id="wt" class="slsh-area" placeholder="Write a Japanese sentence here..."></textarea><button class="slsh-btn" id="wc">Check sentence</button><div class="slsh-box" id="wr">This is a lightweight client-side helper, not a replacement for a real AI language model.</div>');document.getElementById('wc').onclick=()=>{let v=document.getElementById('wt').value.trim();document.getElementById('wr').textContent=!v?'Write a sentence first.':(v.includes('。')?'Good: your sentence has a Japanese full stop. Review particles and natural phrasing with the Study Assistant for deeper help.':'Tip: consider adding 。 at the end when appropriate.')}},
 pronunciation(){html('🎤 Pronunciation Practice','<div class="slsh-box"><button class="slsh-btn" id="rec">Start recording</button><button class="slsh-btn" id="stop" disabled>Stop</button><audio id="aud" controls style="display:block;width:100%;margin-top:12px"></audio></div><p>This tool records your practice so you can listen back. Automatic pronunciation scoring requires a speech/AI service and is not faked here.</p>');let rec,ch=[];document.getElementById('rec').onclick=async()=>{try{let st=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(st);rec.ondataavailable=e=>ch.push(e.data);rec.onstop=()=>{document.getElementById('aud').src=URL.createObjectURL(new Blob(ch,{type:'audio/webm'}));st.getTracks().forEach(t=>t.stop())};rec.start();document.getElementById('rec').disabled=true;document.getElementById('stop').disabled=false}catch(e){alert('Microphone permission is required.')}};document.getElementById('stop').onclick=()=>{rec&&rec.stop();document.getElementById('stop').disabled=true}},
 vocab(){let w=load('words',[]);html('📖 Vocabulary Notebook','<input id="vw" class="slsh-input" placeholder="Japanese word"><input id="vm" class="slsh-input" placeholder="Meaning" style="margin-top:8px"><button class="slsh-btn" id="va">Save word</button><ul class="slsh-list" id="vl">'+w.map(x=>'<li><b>'+x.w+'</b> — '+x.m+'</li>').join('')+'</ul>');document.getElementById('va').onclick=()=>{let nw=document.getElementById('vw').value.trim(),nm=document.getElementById('vm').value.trim();if(nw){w.push({w:nw,m:nm});save('words',w);render.vocab()}}},
 groups(){html('👥 Study Groups','<div class="slsh-row"><div class="slsh-box"><b>N5 Group</b><p>Beginner practice space</p></div><div class="slsh-box"><b>N4 Group</b><p>Intermediate practice space</p></div><div class="slsh-box"><b>N3 Group</b><p>Advanced practice space</p></div></div><p>For a real shared community, connect these groups to your existing Firebase forum system with moderation rules.</p>')},
 qa(){let q=load('qa',[]);html('❓ Q&A Section','<textarea id="qq" class="slsh-area" placeholder="Ask a study question..."></textarea><button class="slsh-btn" id="qaadd">Save question</button><ul class="slsh-list">'+q.map(x=>'<li>'+x+'</li>').join('')+'</ul>');document.getElementById('qaadd').onclick=()=>{let x=document.getElementById('qq').value.trim();if(x){q.unshift(x);save('qa',q);render.qa()}}},
 moderation(){html('🛡️ User Moderation','<div class="slsh-box">Use this workspace alongside your existing Admin Panel role controls. Moderation actions should be enforced by Firebase Rules or trusted server-side code.</div><button class="slsh-btn" id="ml">Record moderation review</button>');document.getElementById('ml').onclick=()=>{let a=load('audit',[]);a.unshift({at:new Date().toISOString(),action:'Moderation workspace opened/review recorded'});save('audit',a);alert('Audit entry saved locally.')}},
 audit(){let a=load('audit',[]);html('📝 Audit Log','<div class="slsh-box"><ul class="slsh-list">'+(a.length?a.map(x=>'<li>'+x.at+' — '+x.action+'</li>').join(''):'<li>No local audit entries yet.</li>')+'</ul></div>')},
 backup(){html('💾 Automatic Backup / Export','<div class="slsh-box"><button class="slsh-btn" id="ex">Export local learning data</button><p>Exports this device’s SL Sakura learning data as JSON. Firebase server data should be backed up separately from the Firebase console.</p></div>');document.getElementById('ex').onclick=()=>{let o={};Object.keys(localStorage).filter(k=>k.startsWith(K)).forEach(k=>o[k]=localStorage.getItem(k));let b=new Blob([JSON.stringify(o,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='sl-sakura-learning-backup.json';a.click();URL.revokeObjectURL(a.href)}}
};
// Show the hub as soon as the existing login UI settles.
window.addEventListener('load',()=>setTimeout(showHub,700));
})();
